name: Deploy Theme to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "Host: ${{ secrets.HOST }}"
          echo "Username: ${{ secrets.USERNAME }}"
          echo "Port: ${{ secrets.PORT }}"
          echo "Theme dir: ${{ secrets.THEME_DIR }}"
          echo "Checking SSH key..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-keygen -l -f /dev/stdin || echo "Invalid SSH key"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "${{ secrets.THEME_DIR }}" ]; then
              echo "Directory ${{ secrets.THEME_DIR }} does not exist"
              exit 1
            fi
            cd ${{ secrets.THEME_DIR }}
            git fetch --all
            git reset --hard origin/main
            git pull origin main