name: Deploy Theme to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug
        run: echo "Deploying to ${{ secrets.HOST }}:${secrets.THEME_DIR }}"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.THEME_DIR }} || { echo "Directory not found"; exit 1; }
            git fetch --all
            git reset --hard origin/main
            git pull origin main